namespace DataTransfer.Character;

public record CharacterHealthUpdate(int CurrentHitPoints);
public record CharacterSpellSlotUpdate(int Level, int Used);
public record CharacterPatchDto(CharacterHealthUpdate? Health, CharacterSpellSlotUpdate? SpellSlot);

public record CharacterUpdateDto(
    string Name,
    byte[] Image,
    int HitPoints,
    string HitDice,
    int ArmorClass,
    string Speed,
    string Race,
    string Class,
    int Level,
    string Background,
    string Traits,
    string Attacks,
    string Spells,
    string Inventory,
    int Strength,
    int Dexterity,
    int Constitution,
    int Intelligence,
    int Wisdom,
    int Charisma,
    int SavingThrowStrength,
    int SavingThrowDexterity,
    int SavingThrowConstitution,
    int SavingThrowIntelligence,
    int SavingThrowWisdom,
    int SavingThrowCharisma,
    int Acrobatics,
    int AnimalHandling,
    int Arcana,
    int Athletics,
    int Deception,
    int History,
    int Insight,
    int Intimidation,
    int Investigation,
    int Medicine,
    int Nature,
    int Perception,
    int Performance,
    int Persuasion,
    int Religion,
    int SlightOfHand,
    int Stealth,
    int Survival,
    SpellSlot FirstLevelSpellSlot,
    SpellSlot SecondLevelSpellSlot,
    SpellSlot ThirdLevelSpellSlot,
    SpellSlot FourthLevelSpellSlot,
    SpellSlot FifthLevelSpellSlot,
    SpellSlot SixthLevelSpellSlot,
    SpellSlot SeventhLevelSpellSlot,
    SpellSlot EighthLevelSpellSlot,
    SpellSlot NinthLevelSpellSlot);
