// <auto-generated />
using Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(PenAndPaperDatabase))]
    partial class PenAndPaperDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Database.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("GameMasterId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Backend.Database.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Backend.Database.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveCampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int>("GridSize")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsGridActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Script")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCampaignId")
                        .IsUnique();

                    b.HasIndex("CampaignId");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Backend.Database.Models.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Acrobatics")
                        .HasColumnType("integer");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AnimalHandling")
                        .HasColumnType("integer");

                    b.Property<int>("Arcana")
                        .HasColumnType("integer");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("Athletics")
                        .HasColumnType("integer");

                    b.Property<double>("ChallengeRating")
                        .HasColumnType("double precision");

                    b.Property<int>("Charisma")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionImmunities")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Constitution")
                        .HasColumnType("integer");

                    b.Property<string>("DamageImmunities")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DamageResistances")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Deception")
                        .HasColumnType("integer");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("History")
                        .HasColumnType("integer");

                    b.Property<string>("HitDice")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("Insight")
                        .HasColumnType("integer");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<int>("Intimidation")
                        .HasColumnType("integer");

                    b.Property<int>("Investigation")
                        .HasColumnType("integer");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Medicine")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Nature")
                        .HasColumnType("integer");

                    b.Property<int>("Perception")
                        .HasColumnType("integer");

                    b.Property<int>("Performance")
                        .HasColumnType("integer");

                    b.Property<int>("Persuasion")
                        .HasColumnType("integer");

                    b.Property<int>("Religion")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowCharisma")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowConstitution")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowDexterity")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowIntelligence")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowStrength")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowWisdom")
                        .HasColumnType("integer");

                    b.Property<string>("Senses")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<int>("SlightOfHand")
                        .HasColumnType("integer");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Stealth")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Survival")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Backend.Database.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Tokens");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CampaignUser", b =>
                {
                    b.Property<int>("PlayerCampaignsId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerCampaignsId", "PlayersId");

                    b.HasIndex("PlayersId");

                    b.ToTable("CampaignUser");
                });

            modelBuilder.Entity("Backend.Database.Models.CharacterToken", b =>
                {
                    b.HasBaseType("Backend.Database.Models.Token");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterTokens");
                });

            modelBuilder.Entity("Backend.Database.Models.MonsterToken", b =>
                {
                    b.HasBaseType("Backend.Database.Models.Token");

                    b.Property<int>("MonsterId")
                        .HasColumnType("integer");

                    b.HasIndex("MonsterId");

                    b.ToTable("MonsterTokens");
                });

            modelBuilder.Entity("Backend.Database.Models.Campaign", b =>
                {
                    b.HasOne("Backend.Database.Models.User", "GameMaster")
                        .WithMany("GameMasterCampaigns")
                        .HasForeignKey("GameMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMaster");
                });

            modelBuilder.Entity("Backend.Database.Models.Character", b =>
                {
                    b.HasOne("Backend.Database.Models.Campaign", "Campaign")
                        .WithMany("Characters")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Database.Models.Map", b =>
                {
                    b.HasOne("Backend.Database.Models.Campaign", "ActiveCampaign")
                        .WithOne("ActiveMap")
                        .HasForeignKey("Backend.Database.Models.Map", "ActiveCampaignId");

                    b.HasOne("Backend.Database.Models.Campaign", "Campaign")
                        .WithMany("Maps")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCampaign");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("Backend.Database.Models.Token", b =>
                {
                    b.HasOne("Backend.Database.Models.Map", "Map")
                        .WithMany("Tokens")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("CampaignUser", b =>
                {
                    b.HasOne("Backend.Database.Models.Campaign", null)
                        .WithMany()
                        .HasForeignKey("PlayerCampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.User", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Database.Models.CharacterToken", b =>
                {
                    b.HasOne("Backend.Database.Models.Character", "Character")
                        .WithMany("Tokens")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Token", null)
                        .WithOne()
                        .HasForeignKey("Backend.Database.Models.CharacterToken", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Backend.Database.Models.MonsterToken", b =>
                {
                    b.HasOne("Backend.Database.Models.Token", null)
                        .WithOne()
                        .HasForeignKey("Backend.Database.Models.MonsterToken", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Database.Models.Monster", "Monster")
                        .WithMany("Tokens")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");
                });

            modelBuilder.Entity("Backend.Database.Models.Campaign", b =>
                {
                    b.Navigation("ActiveMap");

                    b.Navigation("Characters");

                    b.Navigation("Maps");
                });

            modelBuilder.Entity("Backend.Database.Models.Character", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Backend.Database.Models.Map", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Backend.Database.Models.Monster", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Backend.Database.Models.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("GameMasterCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
