name: Publish Client

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    #- name: Setup MSBuild.exe
    #  uses: microsoft/setup-msbuild@v1.0.2

    #- name: Execute unit tests
    #  run: dotnet test

    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}\publish
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.DOTNET_ROOT }}\publish
