name: Publish Client

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    #- name: Execute unit tests
    #  run: dotnet test

    - name: Restore Dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish Client/Client.csproj -c Release -o ./publish

    - name: Get Project Version
      id: version
      run: echo "::set-output name=version::$(dotnet list MyProject/MyProject.csproj package --format nuspec | grep '<version>' | sed -e 's/.*<version>\([^<]*\)<\/version>.*/\1/')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        files: ./publish/*
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
