name: Update Server

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DockerImageName: pen_and_paper_server:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Build Docker image
        run: docker build -t pen_and_paper_server .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag pen_and_paper_server ${{ secrets.DOCKERHUB_USERNAME }}/pen_and_paper_server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pen_and_paper_server:latest
